# Generated by Django 5.1.2 on 2024-10-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_patient_foldername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('deliveryDate', models.DateField()),
                ('deliveryTime', models.TimeField()),
                ('deliveryStatus', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('sendNotification', models.BooleanField(default=False)),
                ('additionalNotes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('medicationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_schedule.medication')),
            ],
        ),
    ]
