# Generated by Django 5.1.2 on 2024-10-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryschedule',
            old_name='patient',
            new_name='patientId',
        ),
    ]
