# Generated by Django 5.1.2 on 2024-10-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthworker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='clinic_facility_name',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='special_skills',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='work_location_address',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='healthworkerprofile',
            name='years_of_experience',
        ),
    ]
