# Generated by Django 5.1.2 on 2024-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(max_length=13, null=True)),
                ('firstName', models.CharField(max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255, null=True)),
                ('dateOfBirth', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('emailAddress', models.CharField(max_length=100, null=True)),
                ('addressLine1', models.CharField(max_length=255, null=True)),
                ('addressLine2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('postalCode', models.CharField(max_length=4, null=True)),
                ('chronicCondition', models.CharField(max_length=255, null=True)),
                ('allergies', models.CharField(max_length=3000, null=True)),
                ('medications', models.CharField(max_length=3000, null=True)),
                ('contactName', models.CharField(max_length=255, null=True)),
                ('contactNumber', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
